### ISSUE TITLE
Mention where to file bugs with `snap` (the application) on the site

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam-archive/snapcraft.io-static-pages#191]
Nowhere on the site (that I could find) directs users to the correct place to file bugs with `snap` the application. The correct place is [on Launchpad](https://bugs.launchpad.net/snappy/+filebug).
## Process

Go to the [community page](http://snapcraft.io/community/). Behold that it doesn't mention the Launchpad bugs list.

I'm not sure whether this should be as a section within the community page or as an item in the footer, or both.

I've also [created a PR](https://github.com/snapcore/snapd/pull/1780) to mention this bugs list in the README for the `snapd` project.

**Comment by barrymcgee** [comment]
@caldav Can you confirm the copy change here? Perhaps this should go in the site-wide footer?

**Comment by caldav** [comment]
I don't think reporting bugs for snapd itself should go in the site-wide footer. We have 4 bug reporting links we ideally want:

- Report a bug on this site (currently in footer)
- Report a documentation bug (https://bugs.launchpad.net/snappy/+bugs?field.tag=snap-docs)
- Report a snapd bug (https://bugs.launchpad.net/snappy/+bugs)
- Report a snapcraft bug (https://bugs.launchpad.net/snapcraft/+bugs)

For #2 I think we should follow what we are doing on docs.ubuntu.com (last item in the left nav)
#3 and #4 should probably go into the respective doc landing pages for snapd/snapcraft and on the community page.

**Comment by matthewpaulthomas** [comment]
In a design review recently, I suggested that the footer contain something like
> You can contribute to **snapd**, **snapcraft**, or **this Web site**.

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#130
