### ISSUE TITLE
Missing documentation on targetting a dedicated custom store

### ISSUE THREAD

**Issue by didrocks** [canonical-webteam-archive/snapcraft.io-static-pages#215]
We got some questions on the ML on how to point snapd on your device image to a custom, inherited store (those are environment variables).

The only existing documentation is at https://myriadrf.org/blog/snap-packages-limesdr/. We should have it as part of the existing snapd documentation

**Comment by caldav** [comment]
Temporarily fixed with https://docs.ubuntu.com/core/en/build-store/upload-snaps, ideally, this will be part of snapcraft.io in the near future
