### ISSUE TITLE
configure hook documentation

### ISSUE THREAD

**Issue by didrocks** [canonical-webteam-archive/snapcraft.io-static-pages#216]
After a discussion on the mailing list, it seems to be unclear when the configure hook is run.

Before, it was only on `snap config <snap_name>`, but it's now executed on snap install and upgrade as well. The documentation should reflect that the hooks are ran during those 2 phases.

**Comment by chadmiller** [comment]
"snap set"?

**Comment by nottrobin** [comment]
@didrocks if this relates to pages under `/docs` in the site, could you file an issue in https://github.com/canonicalltd/snappy-docs mentioning it?

**Comment by didrocks** [comment]
@nottrobin I think in this case, we should have two reference in "Report a bug on this site" from http://snapcraft.io/docs/. I expect most people to click on this when they have a content issue, maybe put the doc part in preferential order and then, do we can triage the other way around? (it seems that @caldav self-assigned this one, and I already referenced it publicly, let's keep it opened and autoclosed on deployment)

**Comment by nottrobin** [comment]
@didrocks Agreed. The way snappy docs is hosted will be changing within the month,we'll try to address this sort of thing at that point.

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#177
