### ISSUE TITLE
All variables that can be used inside a snapcraft.yaml and a startup script should be mentioned

### ISSUE THREAD

**Issue by 3v1n0** [canonical-webteam-archive/snapcraft.io-static-pages#217]
Inside snapcraft.yaml there are some variables such as $SNAPCRAFT_PROJECT_NAME or $SNAPCRAFT_STAGE that are not documented anywhere.

Same for some $SNAP_* env, although it's explained how to see them with an env command.

**Comment by caldav** [comment]
@3v1n0 
"Same for some $SNAP_* env, although it's explained how to see them with an env command." 
Anything missing from: http://snapcraft.io/docs/reference/env ?

**Comment by 3v1n0** [comment]
No, I think that part is fine actually :-).

But you might also add that an user can explore this by doing:
`snap run --shell <snap-name>`

To get a shell he could use to check the environment too.

**Comment by caldav** [comment]
+1

**Comment by tbraeutigam** [comment]
Is there any new documentation for all $SNAPCRAFT_* variables? I can't seem to find any...

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#176
