### ISSUE TITLE
docs: "core" too similar to "ubuntu-core"

### ISSUE THREAD

**Issue by knitzsche** [canonical-webteam-archive/snapcraft.io-static-pages#220]
## Summary

"Core" in snapcraft docs is too similar to ubuntu-core. These two should be more clearly differentiated to avoid reader confusion.

## Process

Open:
http://docs.ubuntu.com/
http://docs.ubuntu.com/core/en/
http://snapcraft.io/docs/core/

Then try to define what "core" means.

## Current and expected result

Readers are not confused by the same term "core" being used to describe different things (ubuntu-core v snapd and related)

## Screenshot

[if relevant, include a screenshot]

**Comment by matthewpaulthomas** [comment]
See also #255.

**Comment by nottrobin** [comment]
Folded into https://github.com/canonical-docs/snappy-docs/issues/170#issuecomment-342184874
