### ISSUE TITLE
UAppExplorer.com link produces white-browser-of-death

### ISSUE THREAD

**Issue by OutsourcedGuru** [canonical-webteam-archive/snapcraft.io-static-pages#231]
## Summary

The [Snapcraft.io home page](http://snapcraft.io/) includes [this link to uappexplorer.com](https://uappexplorer.com/apps?type=snappy) which produces the classic white-browser-of-death (WBoD) screen in browsers like IE11, for example.

## Process

Select the link with IE11, for example.

## Current and expected result

When visiting the indicated link, no actual content is displayed.  I expected some content to be displayed.

## Rationale

Many could argue that those pesky Internet Explorer users ought to go get themselves a decent, god-fearin' browser like Google Chrome or such.  Given that this entirely new "let's all build Snaps" concept is something that needs to be sold to the people.  This might be a good thing.  But people aren't going to buy into this "new, new thing" if there are unreasonable hurdles to jump over, like "just install a different browser".  If you're asking people to completely and radically change the way they produce software and those steps required more work on their part to include digitally-signing code and packaging, etc, etc, at least make the site a little more compatible.  If you put out the **Unwelcome Mat** for IE users then you're losing part of the people you could be compelling to do this "new thing".

## Screenshot

![Uploading White-Browser-Of-Death.png…]()

**Comment by matthewpaulthomas** [comment]
There are no longer any links to uappexplorer.com on the front page.
