### ISSUE TITLE
snapcraft.io/docs should be docs.snapcraft.io

### ISSUE THREAD

**Issue by jamiedbennett** [canonical-webteam-archive/snapcraft.io-static-pages#239]
To be consistent with docs.ubuntu.com snapcraft.io/docs should be docs.snapcraft.io.

**Comment by nottrobin** [comment]
Thanks for raining this. Yes the intention is to move it to either docs.snapcraft.io or docs.ubuntu.com/snapcraft. Is there a compelling reason for it to be the former?

**Comment by jamiedbennett** [comment]
There is no specific reason for the docs.snapcraft.io <http://docs.snapcraft.io/>, just a need to keep it consistent. If it is to move to docs.u.c then that is fine. Can you tell me what the timeline for this move?

Regards,
Jamie.

**Comment by magdalena-mirowicz** [comment]
@jamiedbennett it's not a massive amount of work (can be done within a 2-week sprint) but it's not at the top of our backlog at the moment. If you would like to get it prioritised please speak to Thibaut to bring it up in our next stakeholder planning meeting; we could then commit for the end of January.

**Comment by matthewpaulthomas** [comment]
snapcraft.io is currently presented as mostly OS-agnostic: the lede says “every Linux desktop, server, cloud or device”, accompanied by many OS logos of which Ubuntu is just one. Presumably this is deliberate, to encourage adoption on other OSes. If so, moving the “docs” to docs.ubuntu.com would subvert this somewhat.

Separately, docs.ubuntu.com’s navigation is such that you can’t obviously get from any project’s “documentation” to the rest of that project’s site. This is a problem if you’ve arrived from Web search results or any other site. It would be extremely impressive if docs.ubuntu.com grew the ability to have identical navigation to the various sites that it hosts documents for. Unless that’s implemented, though, consistent navigation is probably much easier to achieve on docs.snapcraft.io.

**Comment by nottrobin** [comment]
@matthewpaulthomas I have some sympathy with the argument that Snapcraft docs would ideally not live on an "Ubuntu" domain. However, the pressing concern here is to get the docs off the main site and onto the central docs service to be consistent with other documentation, and where it can take advantage of the other features of that platform. I haven't heard any objection to the docs.ubuntu.com domain from the maintainers of the Snapcraft docs, and so I don't think we should consider the domain name to be blocker to this work.

Once https://github.com/ubuntudesign/docs.ubuntu.com/issues/13 is implemented, we could then discuss moving the Snapcraft docs to docs.snapcraft.io. But as things stand I don't think the move should wait for that to be implemented.

I agree entirely with your separate point that documentation on docs.ubuntu.com should have an obvious link back to the related brochure site. Would you do me a huge favour and file that as a separate [issue on docs.ubuntu.com](https://github.com/ubuntudesign/docs.ubuntu.com/issues/new) where we can continue the discussion?

**Comment by evandandrea** [comment]
> I haven't heard any objection to the docs.ubuntu.com domain from the maintainers of the Snapcraft docs, and so I don't think we should consider the domain name to be blocker to this work.

Allow me to raise an objection. Snaps are designed to be cross-platform and vendor-neutral. We tell upstreams that this is a great way to package your software once for all the distributions. We tell distributions that this gives them access to software from big names that would've otherwise been only available on Ubuntu.

When we put documentation for snapd, snapcraft, or any other part of the snap ecosystem up on ubuntu.com, we make it harder for the people fighting against the line that snaps are here to strengthen Ubuntu's position over the other distributions:

* https://news.ycombinator.com/item?id=13560236
* https://vizzzion.org/blog/2017/02/plasma-meeting-web-browsers-and-app-bundles/#comment-25652

**Comment by nottrobin** [comment]
Thanks @evandandrea and @matthewpaulthomas, I hear you, and as I said I do appreciate the point.

I am now hoping that https://github.com/ubuntudesign/docs.ubuntu.com/issues/13 will be implemented fairly soon now, and so I will try to make the argument that the move over to the docs platform should wait until it is ready. I'll try to keep you updated here.

**Comment by matthewpaulthomas** [comment]
As requested, I’ve reported ubuntudesign/docs.ubuntu.com#37 on the docs.ubuntu.com navigation problem.

**Comment by matthewpaulthomas** [comment]
Done a few weeks ago.
