### ISSUE TITLE
Long pages cut off when printing in Firefox

### ISSUE THREAD

**Issue by kern-xx** [canonical-webteam-archive/snapcraft.io-static-pages#240]
1. In Firefox, go to any of these pages:
   - https://snapcraft.io/create/
   - https://snapcraft.io/docs/snaps/philosophy
2. Choose Print Preview, or Print to a PDF.

What you see: Most of the page is missing.

What you should see: The whole page is printable.

The problem does not happen in Chromium or Opera.

See also #313, a similar problem with the snapcraft.io/ front page.

**Comment by caldav** [comment]
Hello, I'm sorry but at the time being we do not have issued pdfs that document creating snaps.

I don't really understand the issue, though, here is an example of printing the http://snapcraft.io/create tutorial to PDF (using Opera).

[output.pdf](https://github.com/ubuntudesign/snapcraft.io/files/663326/output.pdf)

**Comment by kern-xx** [comment]
Hello David,
      
      Thanks for your quick response.  My problem is that when learning
      new software I work from printed material, and attempting to print
      from your web site does not work (the output is always truncated
      to one page, which I have *never* seen before).  So, I was looking
      for a pdf.  You sent me one -- many thanks. Your file output.pdf
      is perfectly fine.
      
      I think there is a problem with your site.  When I go to the URL 
      
           http://snapcraft.io/create/
      
      and I use Ubuntu 14.04 Firefox to print to either my printer or a
      pdf, I get the attached pdf.   Note: it is truncated and thus
      useless.  
      
      I know it is work, but a lot of people including myself prefer
      .pdf's.  We can download them and have them online and print all
      or as little as we want.
      
      I am looking forward to using Snaps for Bacula in the near future.
      
      Best regards,
      Kern
      Bacula Project Manager
      
      
      
      On 12/20/2016 10:40 AM, David Callé wrote:
    
    
      Hello, I'm sorry but at the time being we do not have issued
        pdfs that document creating snaps.
      I don't really understand the issue, though, here is an example
        of printing the http://snapcraft.io/create
        tutorial to PDF (using Opera).
      output.pdf
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ubuntudesign/snapcraft.io","title":"ubuntudesign/snapcraft.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ubuntudesign/snapcraft.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@caldav in #240: Hello, I'm sorry but at the time being we do not have issued pdfs that document creating snaps.\r\n\r\nI don't really understand the issue, though, here is an example of printing the http://snapcraft.io/create tutorial to PDF (using Opera).\r\n\r\n[output.pdf](https://github.com/ubuntudesign/snapcraft.io/files/663326/output.pdf)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ubuntudesign/snapcraft.io/issues/240#issuecomment-268198464"}}}

**Comment by matthewpaulthomas** [comment]
(I’ve edited this to cover the actual problem, that printing from the Web site often doesn’t work. Providing separate PDFs would be one possible solution to this problem, but probably not the best solution.)

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#172
