### ISSUE TITLE
Is a Ubuntu Core overview needed in this section?

### ISSUE THREAD

**Issue by liu-xiao-guo** [canonical-webteam-archive/snapcraft.io-static-pages#255]
http://snapcraft.io/docs/core/

Some developers may want to know more about the stack of Ubuntu Core like:

third party snaps
Core OS snap
Gadget snap
Kernel snap
hardware

https://docs.google.com/document/d/172iM3jTkg2os8HgqtSpVug3IR5pjqS2zz607hTi3KVg/edit#heading=h.jc2o5jfemcup
this seems a good article to describe the components

**Comment by knitzsche** [comment]
I think there should simply be a link to the ubuntu core docs. This would eliminate duplicate explanations and refine and strengthen the purpose & identity of each site.

**Comment by matthewpaulthomas** [comment]
If the reason people would expect info about Ubuntu Core here is that it’s called “Core”, maybe it should have a different name.

(Incidentally, he sentence “The snapd technology is the core that powers snaps” is deeply confusing. What on earth is “snapd technology”? There hasn’t been any mention of snapd yet. What does it mean by “core”? That isn’t explained anywhere on the page. And what does it mean by “powers”?)

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#170
