### ISSUE TITLE
using command to push and release a snap

### ISSUE THREAD

**Issue by liu-xiao-guo** [canonical-webteam-archive/snapcraft.io-static-pages#258]
http://snapcraft.io/create/

on the page:
30 - STORE

Open the URL that was returned from snapcraft push or open the snap from the developer portal front page: https://myapps.developer.ubuntu.com

"snapcraft push" command is not shown there. How should be used? what is the difference between "snapcraft upload"? normally, 

$ snapcraft push *.snap --release=stable  

or I can do push first, and then release.

The commands there are not so clear.

**Comment by nottrobin** [comment]
The Create page no longer exists, and instead forwards to https://docs.snapcraft.io/build-snaps/.

If these issues persist, please file another issue on the https://github.com/canonical-docs/snappy-docs repository. Thanks.
