### ISSUE TITLE
Typo in "Defining parts in snapcraft.yaml"

### ISSUE THREAD

**Issue by dshcherb** [canonical-webteam-archive/snapcraft.io-static-pages#259]
## Typo in "Defining parts in snapcraft.yaml"

"way" should be plural.
http://snapcraft.io/docs/build-snaps/parts
"Defining parts in snapcraft.yaml
plugin	(string)	Specifies the plugin that will manage this part. Snapcraft will pass the plugin all the other user-specified part options, those options defined with the other keys below. There are three **way** in which the plugin can be defined: a plugin name to use a built-in plug-in (for details, see the list of built-in plugins), a local path such as parts/plugins/x-plugin_name.py to use a local (custom defined) plugin and if plugin is not defined locally, the plugin defined for the part in the remote parts repository."

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#168
