### ISSUE TITLE
How to publish your own part?

### ISSUE THREAD

**Issue by liu-xiao-guo** [canonical-webteam-archive/snapcraft.io-static-pages#262]
http://snapcraft.io/create/

Frankly, I never know how to publish my part. Do we need to have a tutorial for this telling developers how to share their part?

===========================================
sharing: sharing your parts with other developers

If you would like to publish your own parts, you can contribute them on the wiki at https://wiki.ubuntu.com/snapcraft/parts.

Your contributions will always be welcome!
==========================================

**Comment by nottrobin** [comment]
This section has now been removed, and forwards you to https://docs.snapcraft.io/build-snaps/ instead. Please file a new issue over on https://github.com/canonical-docs/snappy-docs if this is still a problem.
