### ISSUE TITLE
Should we link to snap tutorials prominently on this site?

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam-archive/snapcraft.io-static-pages#268]
I'm forwarding a point made by Tim Peeters over email:

> The tutorials look good. Since currently the first source to learn about snapcraft is snapcraft.io, I propose to link to the new tutorials website from there.

**Comment by caldav** [comment]
That's a good point. Note that it's linked from two pages already: at the end of docs/build-snaps and docs/build-snaps/your-first-snap

**Comment by matthewpaulthomas** [comment]
The global header currently links to the front page of the Tutorials site, so I guess this is fixed. ([tutorials.ubuntu.com#357](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/357) prevents the link from going to snap packaging tutorials specifically.)

In the long run, though, I think we should replace this with more links to individual tutorials. People can’t be expected to know whether the information they want is written as a “tutorial” (or a “doc”, for that matter), so it’s not a useful signpost.
