### ISSUE TITLE
'Setting up environment' undocumented

### ISSUE THREAD

**Issue by stub42** [canonical-webteam-archive/snapcraft.io-static-pages#302]
## Summary

environment variable definitions for apps is mentioned in the release notes ( 'Setting up environment' at https://insights.ubuntu.com/2017/02/17/snapcraft-2-27-has-been-released/ ), but otherwise appears to be undocumented.

**Comment by matthewpaulthomas** [comment]
The environment variable was described a “feature flag” in 2.27, where “the tentative plan is for this to be the default in snapcraft 2.28”. And indeed, [the 2.28 release notes](https://forum.snapcraft.io/t/released-snapcraft-2-28/92) announced that “Delta uploads are now enabled for every snapcraft push done”, making the variable obsolete.

**Comment by stub42** [comment]
This issue is about the 'Setting up environment' section of https://insights.ubuntu.com/2017/02/17/snapcraft-2-27-has-been-released, not the environment variables being used as feature flags.

The feature is still not mentioned at https://docs.snapcraft.io/build-snaps/syntax , which is where I'd expect to find it. Nor https://docs.snapcraft.io/build-snaps/metadata#declaring-app-commands, which is still promoting wrappers which this feature should make unnecessary in many cases.

**Comment by matthewpaulthomas** [comment]
Sorry, I don’t know how I misread that.

**Comment by Lukewh** [comment]
I've added this issue to the docs repo: https://github.com/canonical-docs/snappy-docs/issues/148
