### ISSUE TITLE
philosophy page needs a proofreader

### ISSUE THREAD

**Issue by jekriske-lilly** [canonical-webteam-archive/snapcraft.io-static-pages#309]
https://snapcraft.io/docs/snaps/philosophy

This page could use a little TLC. It's riddled with grammar and spelling errors. ie: "stenza" should be "stanza" etc. Sentences don't make sense, example: 

> This is for all those reasons you should always start developing your snap in devmode: ensure you define confinement: devmode in your snapcraft.yaml stenza and install your package with --devmode.

**Comment by nottrobin** [comment]
Folded into https://github.com/canonical-docs/snappy-docs/issues/156
