### ISSUE TITLE
Pitch snaps to end users

### ISSUE THREAD

**Issue by evandandrea** [canonical-webteam-archive/snapcraft.io-static-pages#311]
Right now we make little effort to sell end users on why they should install snap support. There is a grid of distribution logos on the front page, with links off to specific install instructions for each. We have a "featured applications" grid, but it's buried way down at the bottom of a very long page.

One option would be to carve out space to highlight the most high profile applications available as snaps, above the snapd installation instructions. It may be worth also providing [the total count of snaps available](http://electron.atom.io/apps/) or some bullet points on why they should prefer snaps over traditional packages, provided this doesn't push the actual install instructions too far down.

**Comment by evandandrea** [comment]
We've got some great logos to use for this:

![](http://electron.atom.io/images/apps/discord-icon-64.png) ![](http://electron.atom.io/images/apps/visual-studio-code-icon-64.png) ![](http://electron.atom.io/images/apps/atom-icon-64.png)
![](http://electron.atom.io/images/apps/simplenote-icon-64.png) ![](http://electron.atom.io/images/apps/ghost-icon-64.png) ![](http://electron.atom.io/images/apps/rocket-chat-icon-64.png)
![](http://electron.atom.io/images/apps/mattermost-icon-64.png) ![](http://electron.atom.io/images/apps/wordpress-com-icon-64.png) ![](https://avatars1.githubusercontent.com/gitterHQ?&s=64)

That's Discord, Visual Studio Code, Atom, Simplenote, Ghost, RocketChat, Mattermost, Wordpress, and Gitter.

**Comment by carlaberkers** [comment]
It all depends on the target audience for the page. In this case it was a conscious (Mark driven) decision to focus on the app developer rather then the end user. Snapcraft is a tool for developers so the end users are a secondary audience at best, especially on the homepage.

We shouldn't change the home page hierarchy unless we have very clear direction to do so, but I'm happy to discuss other options of pitching snaps to end users, if this is important.

**Comment by evandandrea** [comment]
Yes, that makes a lot of sense to me. I think we still need a small place to pitch end users on installing snap support.

**Comment by Ads20000** [comment]
@evandandrea Snapcraft is the packaging tool though, 'Snappy' is the general thing (with `snapd` doing the under-the-hood work)?

Imho a better move would be to have Snapcraft install instructions when you click on a distro icon on the homepage as well as `snapd` install instructions if this is going to be focused on the packaging process (Snapcraft) rather than on the installing side of things (`snapd`), though this might require a bit of moving things around. Also maybe an app thing like you're suggesting could go somewhere more prominent to show developers that there are snaps of other apps.

I think I understand all the different names (Snappy being the overarching name; `snapd` doing the work, Snapcraft being the packaging tool, Snaps are individual Snaps), though it does seem very slightly confused to me. Not sure what could be done to make that better, maybe to have separate Snapcraft and Snap sites. The former being developer-facing and the latter being user-facing. Though why users need to go to the site I don't know.

But I'm just a random community member, it's up to you of course!

**Comment by matthewpaulthomas** [comment]
I agree with @Ads20000: Having three different brand names, and a package with a fourth name, puts us at a disadvantage against competing systems. Retiring one or two of those names would help. It reminds me of when Launchpad’s individual apps had separate brands (“Malone”, “Rosetta”, “Soyuz”), before we realized it was a needless complication. (It’s also a complication that the “snapcraft.io” domain does, and is planned to do more, tasks — auto-building, manual uploading, promoting to stable, setting prices, analytics — that don’t/won’t require using Snapcraft-the-tool at all.)

Meanwhile, I’ve had the grid of featured snaps on the front page moved above the instructions (#324), not to interest end users, but to establish credibility for developers. Pitching snaps to end users will be hard to do without either a Web UI for the store, or a way to invoke the native UI from the Web (like the `apt:` URL protocol for Ubuntu Software Center).

**Comment by matthewpaulthomas** [comment]
FWIW, a wireframe I did for this page in June:
![use-snaps-page](https://user-images.githubusercontent.com/19801137/30826737-a0eec18c-a205-11e7-9818-a935e83e8605.png)

The navigation would be less awkward if the page was on a separate snaps site, rather than on snapcraft.io.

**Comment by evandandrea** [comment]
@matthewpaulthomas I like this. Would you link to it from the main snapcraft.io page or not?

**Comment by carlaberkers** [comment]
@evandandrea likely, yes - but where this page lives and how we link to it depends on the URL structure of the whole snapcraft.io site and where the store lives. (Also please be aware this page is not an immediate priority).

**Comment by matthewpaulthomas** [comment]
I was confused as to why I hadn’t posted this wireframe before. It turns out that I did, on #347, where I introduced it as “Until the store Web UI is ready…”

**Comment by nottrobin** [comment]
We are rebuilding the homepage - tracked here https://github.com/CanonicalLtd/snappy-design-squad/issues/148 (private). Once this is release, please open further issues is this is still a problem.
