### ISSUE TITLE
Replace favicon with S

### ISSUE THREAD

**Issue by evandandrea** [canonical-webteam-archive/snapcraft.io-static-pages#316]
We should replace the current favicon with a version of the icon Tom Macfarlane made:
![snapcraft_s_800x800_hex](https://cloud.githubusercontent.com/assets/1523179/25798968/1e97a796-33db-11e7-812d-aea538c97744.png)

See also https://github.com/canonical-ols/build.snapcraft.io/issues/722

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#126
