### ISSUE TITLE
Interface documented two times

### ISSUE THREAD

**Issue by murraybd** [canonical-webteam-archive/snapcraft.io-static-pages#319]
## Summary

At this page https://snapcraft.io/docs/reference/interfaces the account-control interface appears two times, only one of which specifies a specific version of snapd is required.

## Process

Visit the web page and read it.

## Current and expected result

I didn't expect the same interface to appear two times.

**Comment by nottrobin** [comment]
Covered in https://github.com/canonical-docs/snappy-docs/issues/151
