### ISSUE TITLE
Debugging doesn't mention 'snap try'

### ISSUE THREAD

**Issue by popey** [canonical-webteam-archive/snapcraft.io-static-pages#334]
## Summary

Feedback from a developer who was having difficulty debugging a snap. They eventually discovered 'snap try', but it's not on the debugging page.

https://snapcraft.io/docs/build-snaps/debugging

The debugging page needs to include a section which mentions snap try and gives an example of its use.

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#160
