### ISSUE TITLE
snapcraft.io/create needs a table of contents

### ISSUE THREAD

**Issue by elopio** [canonical-webteam-archive/snapcraft.io-static-pages#34]
From James Jesudason in https://bugs.launchpad.net/snappy/+bug/1593615

I'm working through http://snapcraft.io/create/ to build my first snap and am finding it very helpful. However the single page manual is very long - it could use a table of contents or being split into multiple pages to make it easier to navigate. I'm forever losing my place as I read something, then scrollback to something that I read earlier.

**Comment by jamiedbennett** [comment]
I agree that this needs tidying up but the mechanism to do so needs discussion. We will discuss this soon and propose a solution.

**Comment by jamiedbennett** [comment]
I suggest we either use a TOC side pane or split the page up into several sequential pages with next/back or both. 

Another option is to move this big document to snapcraft.io/docs/tour and use the facilities there (TOC + multiple pages).

**Comment by nottrobin** [comment]
+1 for moving the /create page into the docs somehow.

**Comment by matthewpaulthomas** [comment]
http://snapcraft.io/create/ now redirects to https://docs.snapcraft.io/build-snaps/, which is a short page with lots of links to other short pages. There’s still a lot to to, but this issue at least is fixed.
