### ISSUE TITLE
Redirecting to tutorial should redirect to the snap list of tutorials not the overall list of tutorials

### ISSUE THREAD

**Issue by campbieil** [canonical-webteam-archive/snapcraft.io-static-pages#341]
## Summary

[Tutorial links should link to the snap tutorials from snapcraft.io]

## Process

[Click on any tutorial link and you're directed to https://tutorials.ubuntu.com/   ]

## Current and expected result

[Instead I would expect to be redirected to https://tutorials.ubuntu.com/?paper-input-label-1=snap if the function was implemented]

## Screenshot

[if relevant, include a screenshot]

**Comment by nottrobin** [comment]
Duplicate of https://github.com/canonical-websites/snapcraft.io/issues/116
