### ISSUE TITLE
interfaces reference should be listed in alphabetical order 

### ISSUE THREAD

**Issue by campbieil** [canonical-webteam-archive/snapcraft.io-static-pages#342]
## Summary

interfaces reference should be listed in alphabetical order in https://snapcraft.io/docs/reference/interfaces 

## Process

Go to https://snapcraft.io/docs/reference/interfaces  . References are not listed in alphabetical order.

## Current and expected result

interfaces reference should be listed in alphabetical order

## Screenshot

[if relevant, include a screenshot]

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#157
