### ISSUE TITLE
Snapcraft prototype: Front page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-webteam-archive/snapcraft.io-static-pages#343]
Tweaks and extensions to the [front page sprint prototype](https://projects.invisionapp.com/d/main#/console/11296954/238852331/preview):

- Adjust tagline so that it’s not just about updates
- Don’t use the phrase “Extends off”
- More specific CTA button
- Briefly clarify snaps vs. snapcraft in the intro text
- Split “See how Snapcraft integrates” into languages/frameworks vs. environments
- Expand “See how Snapcraft integrates” so that it doesn’t require a famous example for each language

**Comment by matthewpaulthomas** [comment]
![front-page](https://user-images.githubusercontent.com/19801137/27324319-c64bb9e0-559c-11e7-9fc5-1407c6edbcb0.png)

@kwm14 This wireframe shows how the front page can provide language integration examples without all of them being showcase apps. Languages that do have showcase examples can begin “Here’s how {name} does it:”, while those that don’t can have a Hello World example instead.

Other changes:
- Adds “Use snaps” top-level navigation as part of #347.
- Tweaks the tagline to avoid implying that snaps are just about updates, demoting mention of updates to the feature gallery.
- Describes the stores in the feature gallery, helping to address the “what is the store?” problem.
- More specific CTA button text.
- Explains snaps vs. Snapcraft in the intro text.

Changed copy:
- Painless software delivery for Linux and IoT.
- Simple to package with your existing tools.
- Reach tens of millions of Linux systems.
- Public, private, and IoT device stores.
- Updates pushed within hours.
- Get started in minutes
- **Snaps** are containerized software packages that are simple to create and even simpler to install. Snap technology is led by Canonical, sponsors of Ubuntu, and you can install snaps on all other major Linux systems as well.
 You can use **Snapcraft** to publish snaps from the command line, or use our auto-build service to publish from GitHub. Because snaps bundle their dependencies, they work everywhere without modification.
- Snapcraft integrates with your language
- Here’s how **Heroku** does it:

**Comment by nottrobin** [comment]
@matthewpaulthomas confirmed this is done
