### ISSUE TITLE
Snapcraft prototype: Snaps overview

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-webteam-archive/snapcraft.io-static-pages#344]
Tweaks and extensions to the [snaps overview sprint prototype](https://projects.invisionapp.com/d/main#/console/11296954/238864840/preview) to address the relevant [sprint findings](https://github.com/CanonicalLtd/snapcraft-design/issues/13):
- “Double login (GitHub + SSO) confusing”
- “Terminology unclear in nav (publish, release, store)”
- “I want to see what my snap looks like in the store”
- “What steps do I need to take and in what order? (to get my snap built, published and in the store)”

**Comment by matthewpaulthomas** [comment]
![ ](https://user-images.githubusercontent.com/19801137/28214052-a7b4e706-68a0-11e7-98fa-6e09f09b6bcb.png)

The Snaps overview would be most useful for indie developers, doing everything themselves. It would answer the basic question: “Do I need to do anything for publishing today?”

**Comment by nottrobin** [comment]
@matthewpaulthomas confirmed this is done
