### ISSUE TITLE
Non-sensical sentence on philosophy page ❤️

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-webteam-archive/snapcraft.io-static-pages#345]
## Summary

> You can have your wrapper script using the same environment variable technique than described on the first stenza

This doesn't make any sense.

## Process

 1. Navigate to https://snapcraft.io/docs/snaps/philosophy#write-data-to-user-path
 2. As an English speaker, try to understand what the last paragraph means

## Current and expected result

Current:
 * It is difficult to understand what is meant

Expected:
 * It should be clear

## Screenshot

N/A

**Comment by matthewpaulthomas** [comment]
Removing “than”, and changing “on” to “in”, would be grammatical but awkward:
> You can have your wrapper script using the same environment variable technique described in the first st[a]nza.

Simpler:
> Your wrapper script can use the same environment variable technique described in the first stanza.

However, this still has the problem that it introduces the (misspelled) word “stanza” without explaining what it means. It’s used once later in the page, but isn’t defined there either.

**Comment by matthewpaulthomas** [comment]
This is part of [snapcraft.io-static-pages#309](https://github.com/canonical-webteam-archive/snapcraft.io-static-pages/issues/309).

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#156
