### ISSUE TITLE
Snapcraft prototype: End-user page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-webteam-archive/snapcraft.io-static-pages#347]
Until the store Web UI is ready, a page on snapcraft.io for users of all target platforms:
- explaining the benefits of snaps
- giving examples of installable snaps
- guiding them through installing snapd if necessary.

**Comment by evandandrea** [comment]
I think we should also show the distribution support on this page.

**Comment by matthewpaulthomas** [comment]
Draft text:

# Snaps: the simple and secure way to install Linux software.

[logos of target systems]

## Why use snaps?

**Simple to install.** Snaps are self-contained, separate from the system. No complex dependencies, and no interfering with each other. Whichever system you’re running, a snap will work the same way.

**Secure to run.** Not only are snaps kept separate, their data is kept separate too. Snaps communicate with each other only in ways that you approve.

**Easy to update.** Updates are automatic, and download only what’s changed. You can test alphas/betas if you want, switching back to stable at any time. And any update can be reversed.

## Is your system snappy?

Try this example:
[example snap:name button]

If a window opens offering a “Hello World” app, you’re all set. Use the same window to find and install snaps.

If it doesn’t work, follow the instructions for your system: Arch, Debian, Fedora, Gentoo, OpenEmbedded/Yocto, openSUSE, OpenWrt, or Ubuntu.

# 1000+ snaps and counting…

[gallery of featured snaps]

# Want an app as a snap?

If you develop an app yourself, it’s easy to **make it a snap**.

If your favorite app isn’t a snap yet, ask the developers and point them to this page.

**Comment by matthewpaulthomas** [comment]
Wireframe:
![use-snaps-page](https://user-images.githubusercontent.com/19801137/27545584-122f7c12-5a88-11e7-8132-cc4595964241.png)

**Comment by nottrobin** [comment]
@matthewpaulthomas confirmed this is done
