### ISSUE TITLE
Snapcraft prototype: GitHub auth page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-webteam-archive/snapcraft.io-static-pages#348]
We used to [use the GitHub app description to explain why we ask](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q68bf3rlr1z3) for the permissions we do: “We use webhooks so that your code builds automatically after each commit. We look at your organizations so that we can show you their repos.”

However, [that text was removed from the auth page](https://github.com/canonical-websites/build.snapcraft.io/issues/322#issuecomment-304281947) when [GitHub redesigned it](https://github.com/canonical-websites/build.snapcraft.io/issues/322#issuecomment-306058303): “both the description and the homepage URL were removed from the OAuth authorization page in an effort to reduce the risk of phishing … I'd recommend surfacing the information you wanted to show to your users in a different way (e.g. by putting it on the page where you link to the OAuth flow).”

In addition, one of the user test participants was surprised at seeing a GitHub page at all. That may be an outlier; but if it is not, that problem could be solved in the same place as explaining the permissions.

One option would be an interstitial page that appears for ~5 seconds before redirecting you to the auth page.

**Comment by matthewpaulthomas** [comment]
![github-auth-interstitial](https://user-images.githubusercontent.com/19801137/27374408-8a692d14-5663-11e7-90ab-d325892b3e8d.gif)

**Comment by nottrobin** [comment]
@matthewpaulthomas confirmed this is done
