### ISSUE TITLE
Redirect needed for /docs/build-snaps/trusty

### ISSUE THREAD

**Issue by caldav** [canonical-webteam-archive/snapcraft.io-static-pages#353]
The following redirect needs to be set in place:
/docs/build-snaps/trusty -> /docs/build-snaps/build-on-lxd-docker

Deployment should be coordinated with https://github.com/CanonicalLtd/snappy-docs/pull/88 (ready to merge)

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#155
