### ISSUE TITLE
Advanced example in Parts

### ISSUE THREAD

**Issue by leeboby** [canonical-webteam-archive/snapcraft.io-static-pages#354]
Is the "nil" a type or a plugin?

> parts:
   example-part:
     type: nil
     stage-packages:
       - gnupg
       - wget
     organize:
       usr/bin: bin
     filesets:
       binaries:
        - bin/*
        - usr/bin/*
       headers:
        - “*.h”
        - -include
     stage:
       - $binaries
       - test/bin/test_app
       - $headers
     prime:
       - $binaries

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#154
