### ISSUE TITLE
Debian distro instructions: snapd now available in stable (== stretch)

### ISSUE THREAD

**Issue by ajdlinux** [canonical-webteam-archive/snapcraft.io-static-pages#355]
## Summary

The Debian install instructions at https://snapcraft.io/docs/core/install-debian and the distro table at https://snapcraft.io/docs/core/install need to be updated to indicate that snapd is available in Debian 9.0 Stretch.

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#153
