### ISSUE TITLE
"Happening now: Snapcraft Office Hours" banner

### ISSUE THREAD

**Issue by evandandrea** [canonical-webteam-archive/snapcraft.io-static-pages#356]
Can we have a [banner/notification](https://docs.vanillaframework.io/en/patterns/notification) on both snapcraft.io and build.snapcraft.io that can easily be toggled on whenever we're about to start [Office Hours](https://www.youtube.com/playlist?list=PLLz665zen7Q4rGzrB9X-rVZ_v5tVYYnEA)?

Bonus points if we could also show it on forum.snapcraft.io.

**Comment by evandandrea** [comment]
I think Google Tag Manager would be a cheap way of toggling, but I don't mean to be prescriptive.

**Comment by nottrobin** [comment]
That's an interesting point. I don't think Google Tag Manager is intended to be an admin panel for live updates to content, but it might work. Writing a little JavaScript snippet to output / update the markup for a banner shouldn't be too hard.

But we'd need to agree where it would appear on the site and what it would look like.

Currently, I have no idea about how forums are hosted or administered, so I can't say how easy it would be to add a similar solution there.

We can discuss the priority of this change in the next prioritisation meeting.

**Comment by nottrobin** [comment]
We may be able to leverage the cookie notification code, and deliver it through GTM
https://github.com/canonical-webteam/cookie-policy

**Comment by nottrobin** [comment]
@evandandrea did you solve this to your satisfaction? Or do you still need work from us? If you still need this could you please add a new issue over on https://github.com/canonical-websites/snapcraft.io ?
