### ISSUE TITLE
Update version number of snap for different operating systems. 

### ISSUE THREAD

**Issue by rajudev** [canonical-webteam-archive/snapcraft.io-static-pages#360]
## Summary
The version numbers mentioned in docs here https://snapcraft.io/docs/core/install have now changed. 
The numbers mentioned in the documentation are now lagging a lot behind the actual version of snap. 

## Process

[list the steps to replicate the issue]
visit https://snapcraft.io/docs/core/install

## Current and expected result
For Debian
Version of snap mentioned for Debian Unstable is 2.21
while the actual version present right now is [2.27](https://tracker.debian.org/pkg/snapd)
similarly it should be changed for all other operating systems

## Screenshot
Too lazy to do this. Take a look at the links

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#152
