### ISSUE TITLE
Fix Get Crafting section

### ISSUE THREAD

**Issue by Ads20000** [canonical-webteam-archive/snapcraft.io-static-pages#368]
## Summary

Get Crafting section on the snapcraft.io homepage has problems.

## Process

Go to snapcraft.io and scroll down to the Get Crafting section.

## Current and expected result

Current:

```
Snaps have a very simple internal structure — you can easily craft them by hand.

But if your code is on GitHub, the easiest way to build a snap is with our auto-build service. Every commit is auto-built, and every successful build is released to the “edge” channel.

Otherwise, you can use Snapcraft, which allows building from source and from existing packages. Snapcraft also handles releasing your snaps to the world.

Read how to create a snap and join the snap-crafting community — we hang out in the #snappy channel on Freenode or snapcraft@lists.snapcraft.io.
```

Expected:

Snapcraft should have a lower-case 's' (third paragraph), also the auto-build service uses snapcraft so 'otherwise' in the third paragraph doesn't make much sense. @matthewpaulthomas [said](https://github.com/canonical-websites/snapcraft.io/issues/311#issuecomment-303977023) that the auto-build service won't need snapcraft in the future but I'm pretty sure that at the moment it does require a `snapcraft.yaml` to build from? When will this change, if ever? If not in the near future then this paragraph seems misleading.

'Read how to create a snap' should link to https://tutorials.ubuntu.com/tutorial/create-first-snap#0 , I think (currently there is no link for this passage), that would make sense as per the merged PR linked below.

'snap-crafting' should be 'snapcrafting', I think (since snapcraft is the build tool, so it would make sense that snapcrafting is the activity of creating a snap, I don't think I've actually seen this term used much elsewhere though)?

The snapcrafting community links needs to be updated to `we have a fun crowd of people who hang out on <a class="external" href="https://rocket.ubuntu.com/channel/snapcraft">Rocket Chat</a> and on the <a class="external" href="https://forum.snapcraft.io/">snapcraft forum</a>.</p>` as per [this merged PR](https://github.com/canonical-websites/www.ubuntu.com/pull/1779) for www.ubuntu.com.

Perhaps someone like @evandandrea has more ideas on how this section should read.

## Screenshot

![screenshot from 2017-09-07 13-43-05](https://user-images.githubusercontent.com/3178485/30163877-8200a204-93d2-11e7-875e-a5ecf69ea85a.png)

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#120
