### ISSUE TITLE
Explain that source: deb does not execute maintainer scripts

### ISSUE THREAD

**Issue by knitzsche** [canonical-webteam-archive/snapcraft.io-static-pages#376]
Explain that for a part with source: deb, the debian maintainer scripts do not execute. Provide a reason why this is the design. Summarize steps a snapper would therefore need to take.

**Comment by jhodapp** [comment]
Seems to be missing from the documentation [here](https://snapcraft.io/docs/build-snaps/syntax) on using a .deb as a part's source.

**Comment by knitzsche** [comment]
A small guide for each type of part may be helpful.

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#150
