### ISSUE TITLE
Add (daily?) updated list of snaps to the website?

### ISSUE THREAD

**Issue by gliptak** [canonical-webteam-archive/snapcraft.io-static-pages#378]
I might have missed the listing on the site.

A current list of all snaps might increase use, as prospective users can check if software of interest is already packaged for snap.

Thanks

**Comment by nottrobin** [comment]
This is planned and tracked internally at https://github.com/canonicalltd/snappy-design-squad/issues/169 and should be implemented over the coming few months.

Until then, please use the `snap find` command.
