### ISSUE TITLE
Update supported operating systems 

### ISSUE THREAD

**Issue by evandandrea** [canonical-webteam-archive/snapcraft.io-static-pages#380]
Please add the following operating systems to the front page:

- Ubuntu MATE
- Manjaro
- Kubuntu
- KDE Neon
- Linux Mint

**Comment by evandandrea** [comment]
Typo: "Ubuntu MATE"

**Comment by evandandrea** [comment]
Worth checking with @popey and @wimpress to see if Antergos can be added when the rest of these are.

**Comment by evandandrea** [comment]
See also https://github.com/canonical-websites/snapcraft.io-static-pages/issues/387

**Comment by caldav** [comment]
@evandandrea @wimpress @popey
Which one of MATE, Kubuntu, KDE Neon, Mint ship snapd by default in their respective latest stable release?
Which one need extra steps? Such as rebooting or enabling snapd through systemctl

**Comment by Lukewh** [comment]
@evandandrea @caldav what's the status of this? Mint and Manjaro have been added but what of the others?

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#118
