### ISSUE TITLE
Front page leads to instructions for installing snapd but not snapcraft

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-webteam-archive/snapcraft.io-static-pages#388]
1\. Go to snapcraft.io.
2\. Click any of the operating system buttons.
3\. Try to find how to install Snapcraft.

What happens:
2\. You are taken to instructions for installing snapd.
3\. Snapcraft isn’t even mentioned on the page.

What should happen: Ideally, the page describes how to install both snapd _and_ snapcraft.

It might save time to fix #315 (Need concise snapcraft install instructions) at the same time as this bug.

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#117
