### ISSUE TITLE
Divided strings

### ISSUE THREAD

**Issue by ktatar156** [canonical-webteam-archive/snapcraft.io-static-pages#39]
At https://translations.launchpad.net/snapcraft.io should be some comments for translators, like: "don't translate that, it's a command to be run in terminal".

And strings shouldn’t be divided (like Anthony Wong mentioned at translators mailing list)

"An example is this sentence on the front page:
Click for installation instructions, or build snapd from source.

It is broken down into 4 parts: "Click for installation instructions, or ", "build", "snapd", and "from source". I think the intention is to leave the HTML codes out but this is not a good idea in this case. The end result will look weird in some languages that don't have the same grammar as English."

**Comment by anthonydillon** [comment]
Thanks @ktatar156 I did notice the splits. I will try and work on the script that pulls these strings out and make it ignore `<code>` blocks as just keeps them as full strings. I dont know we can remove the `<code>` blocks from the content as it is semantic there.
