### ISSUE TITLE
The instructions to use a desktop file are confusing

### ISSUE THREAD

**Issue by elopio** [canonical-webteam-archive/snapcraft.io-static-pages#392]
## Summary

In https://snapcraft.io/docs/build-snaps/metadata#fixed-assets, there is a paragraph that says:

> Alternatively, you can create a snap/gui/ directory at the root of your snapcraft project to host a desktop file:
> 
> snap/gui/<app-name>.desktop
> snapcraft.yaml
> 

it doesn't make a lot of sense.

## Process

Open https://snapcraft.io/docs/build-snaps/metadata#fixed-assets

## Current and expected result

That line that says: 
> snapcraft.yaml

It seems that what the instructions is saying is that you need to add the two lines to a file. It might be better to just say:

> Alternatively, you can write your desktop file in `snap/gui/<app-name>.desktop`

## Screenshot

[if relevant, include a screenshot]

**Comment by Lukewh** [comment]
Moved to https://github.com/canonical-docs/snappy-docs/issues/147
