### ISSUE TITLE
External link to Tutorials unfiltered

### ISSUE THREAD

**Issue by Greggless** [canonical-webteam-archive/snapcraft.io-static-pages#393]
## Summary

The primary navigation link to the external [Tutorials site](https://tutorials.ubuntu.com/) should ideally lead to a filtered view of Snap/Snapcraft related tutorials.

This is just a UX recommendation! 👯

**Comment by matthewpaulthomas** [comment]
I thought this would be a one-line fix, but it’s currently impractical because [the search form is not a real submitted form](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/357).

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#116
